import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      colors: {
        background: '#111509',
        surface: '#111509',
        'surface-dim': '#111509',
        'surface-bright': '#373b2d',
        'surface-container-lowest': '#0c0f05',
        'surface-container-low': '#191d11',
        'surface-container': '#1d2115',
        'surface-container-high': '#272c1f',
        'surface-container-highest': '#323629',
        'on-surface': '#e1e4d1',
        'on-surface-variant': '#c3caae',
        'inverse-surface': '#e1e4d1',
        'inverse-on-surface': '#2e3225',
        outline: '#8d947b',
        'outline-variant': '#434935',
        'surface-tint': '#9ed900',
        primary: '#c2ff43',
        'on-primary': '#243600',
        'primary-container': '#a6e214',
        'on-primary-container': '#456100',
        'inverse-primary': '#4a6800',
        secondary: '#c5c6ca',
        'on-secondary': '#2e3133',
        'secondary-container': '#47494c',
        'on-secondary-container': '#b7b8bc',
        tertiary: '#f5e7ff',
        'on-tertiary': '#3c2656',
        'tertiary-container': '#e1c4ff',
        'on-tertiary-container': '#664e81',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        sm: '0.5rem',
        DEFAULT: '1rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '32px',
        xl: '64px',
        gutter: '24px',
      },
      maxWidth: {
        container: '1000px',
      },
    },
  },
  plugins: [],
} satisfies Config
